version: 0.1
log:
  level: info
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: 0.0.0.0:5000
  headers:
    X-Content-Type-Options: [nosniff]
  debug:
    addr: 0.0.0.0:5001
    prometheus:
      enabled: true
      path: /metrics
proxy:
  remoteurl: https://registry-1.docker.io
  username: ""  # Optional: docker hub username
  password: ""  # Optional: docker hub password